theme: jelly-theme-cayman
title: BRIDGES Summer School in the South Pacific
description: " Innovative Prototyping through AI and Open Source <br> 9th â€“ 11th January 2026"
background: ""
repository: bridges-png/bridges-png.github.io/
