theme: jekyll-theme-cayman
title: BRIDGES summer school in the south pacific
description: "BRIDGES-PNG 2026 Summer School on BRIdging the Divides with Globally Engineered Software <br> 9th â€“ 12th January 2026"
background: ""
repository: bridges-png/bridges-png.github.io/
